### ISSUE TITLE
Fix header image

### ISSUE THREAD

**Issue by 0silverback0** [0silverback0/LandingPages#1]
I want to moved and resize the header image so that the headphones are visible  but have the image retain the full with of the device. This should also fix the issue on all size devices

**Comment by Harshsharmaa28** [comment]
@0silverback0 can you assing me this issue.

**Comment by Harshsharmaa28** [comment]
Hello @0silverback0,
Are you building your own website or cloning another website? If you don't have any objections, I'm available to assist and work on creating this website for you.

**Comment by Harshsharmaa28** [comment]
@0silverback0 solved the issue.
