### ISSUE TITLE
Update home tab links

### ISSUE THREAD

**Issue by 0silverback0** [0silverback0/LandingPages#11]
The home tabs on each page in this project should reference the index.html in the root directory. This just makes for easier navigation between pages.

**Comment by sid172014** [comment]
Hey @0silverback0 i hope you're doing good , can you please assign this issue to me?

**Comment by 0silverback0** [comment]
Your assigned

**Comment by manan18** [comment]
This project  looks interesting, I would love to eork on this. Can you please assign me this issue?

**Comment by 0silverback0** [comment]
Done, your assigned!

**Comment by sid172014** [comment]
Hey @0silverback0 i've made a PR #14 for this issue , can you please have a look into it ? and please let me know if there's any change you wanna have...

**Comment by manan18** [comment]
Hey @0silverback0 , I've initiated a pull request for the requested "Update home tab links" #15 . Please have a look.

**Comment by Basim03** [comment]
please assign this to me

**Comment by Basim03** [comment]
Hey @0silverback0 i have started a pull request for the "Update home tab links" #17 please look into it and merge it 
Thank you!

**Comment by 0silverback0** [comment]
this issue appears to be solved if needed again i will open another issue! thank you!
