### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [0silverback0/LandingPages#12]
I want to add a landing page 

https://github.com/0silverback0/LandingPages/assets/127650446/e0e9d841-f600-4c70-a002-9072b84d2c84

can you please assign this to me , I am Very much interested to contribute myself in hacktoberfest_23 : )

**Comment by 0silverback0** [comment]
Make your PR and I'll merge it! Nice work!

**Comment by Bharath-KumarReddy** [comment]
Hi ,
I resolved this issue and I made a PR #16  once please check _hacktoberfest-2023 : )

**Comment by 0silverback0** [comment]
i commented in #16 im going to close this issue
