### ISSUE TITLE
Landing page for "Welcome to landing page repo"

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [0silverback0/LandingPages#13]
![image](https://github.com/0silverback0/LandingPages/assets/127650446/6c468fb7-c361-474b-a14b-bcaca61fdf90)

I want  to change this into a beautiful good looking landing page in which I will use linear gradient , background images and I will use Bootstrap for to display the links in a navbar with good UI .

assign this to me , I  am very much interested to contribute myself in hacktoberfest_23 :)

**Comment by 0silverback0** [comment]
Absolutely this was one I was going to get to but you can surely have it!

**Comment by Basim03** [comment]
Please assign this issue to me so that i can style it beautifully and so that it looks neat and clean
Thank you!
