### ISSUE TITLE
bug: unresponsive navbar in Animated landing page

### ISSUE THREAD

**Issue by MahendraDani** [0silverback0/LandingPages#18]
## Description
The navigation bar in `Animated Landing Page` is unresponsive for mobile devices. As Navigation bar is one of the core components of any landing page it must be responsive for all screens

## How to reproduce
1. Go to https://radiant-cucurucho-b049fa.netlify.app/animated%20landing%20page/
2. Inspect and apply smaller screen size

## Screenshots

![Screenshot (23)](https://github.com/0silverback0/LandingPages/assets/116940083/e3713887-9d9c-40c8-9bc1-dee5a0b5907e)

**Comment by MahendraDani** [comment]
@0silverback0 I want to work on this issue

**Comment by 0silverback0** [comment]
go for it! thanks for the attention to detail

**Comment by Basim03** [comment]
I want to work on this issue please assign this to me as well @0silverback0 
Thank you!

**Comment by 0silverback0** [comment]
assigned

**Comment by Mohan0884** [comment]
Hey @MahendraDani can you please assign me this issue if it is not fixed?

**Comment by 0silverback0** [comment]
@Mohan0884 i dont believe this issue if fixed
