### ISSUE TITLE
landing page 

### ISSUE THREAD

**Issue by Basim03** [0silverback0/LandingPages#19]
The landing page seems very bland and i would like to style it

Please assign me this issue and  #ill work on it 
![Github issue 1](https://github.com/0silverback0/LandingPages/assets/108823665/02f973c4-1764-4db4-b215-4475d51acb3e)

**Comment by 0silverback0** [comment]
i have you and one other assigned to the issue! First come first serve!

**Comment by Basim03** [comment]
@0silverback0 Please review the commits in pull request #17 i have styled the landing page with pure html and css 
Thank You!

**Comment by 0silverback0** [comment]
i have you assigned in #13 and im going to close this issue
