### ISSUE TITLE
needs a proper title and favicon in "Welcome landing page"

### ISSUE THREAD

**Issue by rhnas110** [0silverback0/LandingPages#26]
Hi Sir @0silverback0 
Issue Description:
In the index file for Welcome landing page dont have a favicon and the title is default "Document"

Screenshots:
![image](https://github.com/0silverback0/LandingPages/assets/51848196/7ccce254-ec17-46e1-9d1d-b92871d64c4b)

Can you take my advice and assign this task to me Sir @0silverback0 ? and I'm actually new to open source contributions, I also participated in Hacktoberfest2023.

**Comment by 0silverback0** [comment]
Go for it! Nice attention to detail!
