### ISSUE TITLE
adding glassmorphism effect to the landing page cards 

### ISSUE THREAD

**Issue by Sameersawant77** [0silverback0/LandingPages#27]
pls assign me this issue with hacktoberfest label, would love to contribute ^^

**Comment by 0silverback0** [comment]
@Sameersawant77 sounds cool! go for it!

**Comment by Sreyasree-001** [comment]
can I work on this issue?

**Comment by Sameersawant77** [comment]
> can I work on this issue?

I am currently working on it, you can make changes after my PR 😄

**Comment by 0silverback0** [comment]
hey hows this coming along ?

**Comment by Sameersawant77** [comment]
I was out for weekend 😅, will make a PR for the issue today ✨

**Comment by 0silverback0** [comment]
just checking in! no rush

**Comment by 0silverback0** [comment]
closing this issue! Nice work!
