### ISSUE TITLE
create contact us page in Earworm section of landing page

### ISSUE THREAD

**Issue by Bisalkumar1** [0silverback0/LandingPages#29]

**Comment by Bisalkumar1** [comment]
please assign me this to add contact us page

**Comment by 0silverback0** [comment]
Yea absolutely I've added Hacktoberfest tags as well

**Comment by Basim03** [comment]
I can work on this as well @0silverback0  Please assign it to me as well 
Thank you!

**Comment by 0silverback0** [comment]
@Basim03 im going to create a new issue #30 and assign you to it for creating a footer for the root index.html. I want to see what @Bisalkumar1 does here

**Comment by Basim03** [comment]
but i have already finished the contact page with basic html and css @0silverback0 i just need to get a PR going

**Comment by 0silverback0** [comment]
Ok push it!

**Comment by Basim03** [comment]
Done ! @0silverback0

**Comment by Bisalkumar1** [comment]
this is not fair this issue was assigned to me firstly .

**Comment by 0silverback0** [comment]
Reopened! Go for it!

**Comment by Bisalkumar1** [comment]
ok thanks

**Comment by Bisalkumar1** [comment]
what will I update its created and merged already

**Comment by 0silverback0** [comment]
There's always room to improve it

**Comment by 0silverback0** [comment]
@Bisalkumar1 did you want to make this look better on mobile?

**Comment by Bisalkumar1** [comment]
Ok will do it

**Comment by Bisalkumar1** [comment]
done

**Comment by Bisalkumar1** [comment]
Hey did u merge before closing ??
