### ISSUE TITLE
Create a footer for the root index.html page

### ISSUE THREAD

**Issue by 0silverback0** [0silverback0/LandingPages#30]

**Comment by Basim03** [comment]
Can you please specify what the footer should include?

**Comment by 0silverback0** [comment]
Maybe a Hacktoberfest and GitHub logo the rest is up to you!

**Comment by Basim03** [comment]
alright will try to make it as minimalistic as i can

**Comment by 0silverback0** [comment]
Don't hold back! Make it what you want!

**Comment by Basim03** [comment]
Alright will complete it by eod or maybe tomorrow because got a lot of college work on my hand 
Meanwhile can you assign it to me @0silverback0 
Thanks!

**Comment by 0silverback0** [comment]
Done! No worries
