### ISSUE TITLE
Feature: Landing Pages UI update

### ISSUE THREAD

**Issue by spacesie** [0silverback0/LandingPages#33]
# UI Redesign
- I would like to suggest a few UI updates to the `index.html` of Landing Pages.

## Development
- I can introduce these changes in a PR if accepted and assigned.

## Mockup of suggested improvements
![ui-redesign2](https://github.com/0silverback0/LandingPages/assets/140430987/8b18d1ca-3c4e-4f74-b0ae-eb438c9ca436)

**Comment by 0silverback0** [comment]
you must have read my my mind @beingsie go for it!

**Comment by 0silverback0** [comment]
@beingsie hows this coming along?

**Comment by spacesie** [comment]
> @beingsie hows this coming along?

- Working on this now! Recent merges have been pulled, I have to rework a lot of the new code so that there are no issues when a PR is created.

### Screenshot progress:
<img width="1430" alt="image" src="https://github.com/0silverback0/LandingPages/assets/140430987/5a95ed7a-312b-44c6-b4bb-250bc9ac1396">

**Comment by 0silverback0** [comment]
Cool thanks
