### ISSUE TITLE
Hover Effect in buttons of Gymso Website

### ISSUE THREAD

**Issue by arnabpal2022** [0silverback0/LandingPages#36]
Can I add Beautiful UI Hover effects in the buttons of Gymso Fitness Website?

**Comment by 0silverback0** [comment]
absolutely! your assigned and hacktoberfest tags added!

**Comment by arnabpal2022** [comment]
@0silverback0 Please Check #51

**Comment by 0silverback0** [comment]
closing this issue, nice work!
