### ISSUE TITLE
Home button not visible on mobile in Lioness project

### ISSUE THREAD

**Issue by 0silverback0** [0silverback0/LandingPages#40]
there should be a home button thats visible on this page on mobile that links back to the root directory index.hmtl

**Comment by Basim03** [comment]
Ill take up the task @0silverback0

**Comment by Tusharrgrg** [comment]
hey @0silverback0  can u assign me this? i want to work on this issue.

**Comment by 0silverback0** [comment]
Sure thing! Go for it
