### ISSUE TITLE
[project Portfolio] enhance navbar

### ISSUE THREAD

**Issue by Pooja-Lohar25** [0silverback0/LandingPages#42]
1. Adjust spacing between navbar links
2. Add color 
3. Add hover properties

@0silverback0 Please assign me this issue under hacktoberfest. 

you may also provide any suggestions for the enhancement of the navbar

**Comment by 0silverback0** [comment]
please tell me which navbar you are referencing

**Comment by Pooja-Lohar25** [comment]
> please tell me which navbar you are referencing

Project name - Portfolio
https://radiant-cucurucho-b049fa.netlify.app/portfolio/

![image](https://github.com/0silverback0/LandingPages/assets/73185303/10aa9d7d-fc1b-49ec-b598-eb49fd713af0)

**Comment by 0silverback0** [comment]
Yea please do! Be sure to pull the latest changes because I'm about to merge a bug update to the repo landing page
