### ISSUE TITLE
create a portfolio page with enhanced UI

### ISSUE THREAD

**Issue by Ro-shni** [0silverback0/LandingPages#61]

**Comment by Ro-shni** [comment]
could you please check the latest pull pr #62

**Comment by harshit1142** [comment]
I wanted to add mine.
Please assign this to me.

**Comment by 0silverback0** [comment]
@harshit1142 create a new PR be sure to add your information to the root index.html, and add a link to /index.html in your nav home tab, be sure to make it responsive on all devices please
