### ISSUE TITLE
create a responsive ecommerce landing page

### ISSUE THREAD

**Issue by KRRISHSINGH08** [0silverback0/LandingPages#63]

**Comment by KRRISHSINGH08** [comment]
@0silverback0  Please do check and merge under hacktoberfest

**Comment by 0silverback0** [comment]
i have check it and left comment there, but heres the next steps 

1. have your home tab link to /index.html
2. add your information to the root index.html so your site can be viewed

**Comment by KRRISHSINGH08** [comment]
Please have a look now
