### ISSUE TITLE
Poor Alignment of images in codeBuddy landing page

### ISSUE THREAD

**Issue by sagar803** [0silverback0/LandingPages#67]
Description:
Issue: I came across an alignment issue in the codeBuddy landing page. The Image is not aligned correctly, which affects the user experience.

Expected Behavior:
The image should be properly aligned with the flow of the landing page, creating a visually pleasing and user-friendly appearance.

![Screenshot 2023-10-24 130642](https://github.com/0silverback0/LandingPages/assets/76766163/82111ddb-bb72-4fab-ba2f-960a301a5709)
![Screenshot 2023-10-24 130504](https://github.com/0silverback0/LandingPages/assets/76766163/12db7acf-3927-4e5b-b5e7-17e8ca878b72)

I had understood the requirement, and will be able to fix the issue, PLEASE assign this to me @0silverback0

**Comment by 0silverback0** [comment]
good attention to detail! Go for it!
