### ISSUE TITLE
Crypto landing page 

### ISSUE THREAD

**Issue by harrishDev** [0silverback0/LandingPages#80]
i'll come up with a crypto landing page

**Comment by harrishDev** [comment]
@0silverback0 assign me with hacktoberfest labels

i don't know why but my issues are being closed often 
This is my 3rd time opening a new issue

**Comment by 0silverback0** [comment]
Hi for it be sure to read the guidelines that could be why. Any questions just ask. Also you can always reopen a PR

**Comment by 0silverback0** [comment]
closing this issue, commit is merged
